// Shared configuration/constants used across services.
// DO NOT EDIT THIS FILE. Use ENV variables instead.

// Sensors.
export const SENSORS: string[] = [ 'temperature', 'humidity', 'rssi' ];

// History settings.
export const UNREACHABLE_HOURS: number = Number(process.env.UNREACHABLE_HOURS);
export const LOW_BATTERY_VOLTAGE: number = Number(process.env.LOW_BATTERY_VOLTAGE);
export const CURRENT_HISTORY_MIN_MAX_HOURS: number = Number(process.env.CURRENT_HISTORY_MIN_MAX_HOURS);

// Server settings.
export const { SERVER_PORT, SERVER_SOCKET } = process.env;

// Database settings.
export const {
	DB_HOST,
	DB_USER,
	DB_PASSWORD,
	DB_NAME,
	NODE_ENV
} = process.env;